### PR TITLE
Import paper-styles/color.html to fix wrong opacity on focus

### LINKED ISSUE #61: Opacity is missing on focused menu items background
The background on focused items is full opacity and the same color as the menu item text. This makes the text unreadable.

polymer_starter_kit
## Expected outcome

The opacity of the background for focused menu items should be lower than the text so the text is readable.
## Actual outcome

The opacity is the same as the text so you cannot read the menu item while it is focused.
## Steps to reproduce
1. Put a `paper-menu` element in the page.
2. Open the page in a web browser.
3. Click the `paper-menu > a` element.

Relates to: https://github.com/PolymerElements/polymer-starter-kit/issues/515

### PR DESCRIPTION
**Pull request by tuxracer**
Closes #61

### CODE REVIEW

**Comment by tuxracer** [comment]
I signed it!

**Comment by notwaldorf** [comment]
@tuxracer I don't see where a color from `color.html` is used in `paper-menu`, or `paper-menu-shared-styles`, so I don't know why this import is needed

**Comment by notwaldorf** [comment]
Ah, `--dark-divider-opacity`. I originally thought that was from `default-theme.html`. My bad!

**Comment by notwaldorf** [comment]
@tuxracer I think you might need to add this to `paper-submenu` as well.

**Comment by notwaldorf** [comment]
Thanks!

**Comment by notwaldorf** [comment]
(I think the test failures are unrelated, since they're happening on master as well. Opened https://github.com/PolymerElements/paper-menu/issues/63)

**Comment by addyosmani** [comment]
Thank you for fixing this! Are we planning a 1.2.1 anytime soonishish? :cat:

**Comment by tuxracer** [comment]
@notwaldorf ack good catch on `paper-submenu` @addyosmani no problem!

**Pull request merged**
